### ISSUE TITLE
TrimCharFields

### ISSUE THREAD

**Issue by sluggern67** [zendtech/IbmiToolkit#175] opened 2021-11-24 12:57 UTC
Some Toolkit functions fails when using ODBC transport with TrimCharFields set to 1 (Fixed length char fields are returned without trailing spaces). I don't see any errormessage, the connection just times out.

I've encountered this when getting memberlist from a file with multiple members.

The issue can be seen with 2 minor changes to samples/test_toolkit_odbc.php:
- add ";TRIMCHAR=1" to the connection string.
- Swap "DSPLIBL" with "DSPFD FILE(QSYS/QAWPZSFNT) TYPE(*MBRLIST)" (or any other file with many members) as the ClInteractiveCommand.

**Comment by alanseiden** [comment] 2021-12-09 06:46
Note to all, outside of the toolkit we are working with the issue poster on the root cause of the character encoding issues that led to the use of TrimCharFields.

**Comment by alanseiden** [comment] 2021-12-10 19:40
We are working on the encoding issue at the PDO_ODBC level. https://bugs.php.net/bug.php?id=81688 
Will close this toolkit issue.

**Closed by alanseiden** 2021-12-10 19:40 UTC
